### ISSUE TITLE
Duplicated symbol on OSX

### ISSUE THREAD

**Issue by tito** [matham/ffpyplayer#68] opened 2019-04-29 20:26 UTC
On OSX, i use Kivy compiled on my own, and `pip installed ffpyplayer`.
Everytime i start Kivy with `KIVY_VIDEO=ffpyplayer`, it shows:

```
objc[26207]: Class SDLApplication is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e41378) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6170). One of the two will be used. Which one is undefined.
objc[26207]: Class SDLAppDelegate is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e413c8) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee61c0). One of the two will be used. Which one is undefined.
objc[26207]: Class SDLTranslatorResponder is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e41440) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6238). One of the two will be used. Which one is undefined.
objc[26207]: Class SDLMessageBoxPresenter is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e41648) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6260). One of the two will be used. Which one is undefined.
objc[26207]: Class SDL_cocoametalview is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e41328) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee62b0). One of the two will be used. Which one is undefined.
objc[26207]: Class SDLOpenGLContext is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e41468) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6300). One of the two will be used. Which one is undefined.
objc[26207]: Class SDLWindow is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e414b8) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6350). One of the two will be used. Which one is undefined.
objc[26207]: Class Cocoa_WindowListener is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e414e0) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6378). One of the two will be used. Which one is undefined.
objc[26207]: Class SDLView is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e41558) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee63f0). One of the two will be used. Which one is undefined.
objc[26207]: Class METAL_RenderData is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e415a8) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6440). One of the two will be used. Which one is undefined.
objc[26207]: Class METAL_TextureData is implemented in both /Library/Frameworks/SDL2.framework/Versions/A/SDL2 (0x108e415f8) and /Users/tito/miniconda3/envs/kivy/lib/python3.6/site-packages/ffpyplayer/.dylibs/libSDL2-2.0.0.dylib (0x10aee6490). One of the two will be used. Which one is undefined.
```

**Comment by matham** [comment] 2019-04-29 20:42
@quanon had told me about this a while ago on IRC I think, but he said that it still works so I ignored it. I'm guessing the issue is that we're combining different installs by using kivy through a framework and ffpyplayer that is compiled differently.

I'm not really sure what I can do about this as I don't really understand how osx frameworks etc. work.

**Comment by matham** [comment] 2019-04-29 20:45
Specifically, the wheel is compiled using sdl2 and ffmpeg from brew it seems. Perhaps this is wrong?

**Comment by matham** [comment] 2022-03-29 22:33
Closing as I don't know what we can do. This seems like an issue with how delocate fixes wheels as maybe it needs to do something to make the binaries unique. But there's not much we can do about this except update kivy and ffpyplayer so the sdl2 versions are about the same.

**Closed by matham** 2022-03-29 22:33 UTC
